default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: StreamingPlatform_development

test:
  <<: *default
  database: StreamingPlatform_test
production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
